name: tuto_tache_ddd
description: DDD
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  format_ecran_package:
    path: packages/format_ecran_package
  text_theme:
    path: packages/text_theme
  bloc: ^9.0.0
  equatable: ^2.0.5
  formz: ^0.6.1
  firebase_core: ^3.6.0
  cloud_firestore: ^5.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
dev_dependencies:
  bloc_test: ^10.0.0
  fake_cloud_firestore: ^3.0.5
  flutter_gen_runner: ^5.5.0
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
flutter:
  generate: true
  uses-material-design: true
